### PR TITLE
Adding an option to parse only the minimal subset of modules needed for code generation

### PR DESCRIPTION
**Pull request by ars3niy**
This works by parsing the modules that need to be rebuilt, obtaining names of modules imported by them, matching those to file names, parsing new ones, obtaining names of modules imported by them, and so on until nothing new is left.

In order to get list of modules imported by the one just parsed, the parse functions are made to return Common::Module* pointer to the parsed module.

This can be used to speed up the compilation significantly.

### CODE REVIEW

**Comment by KristofSzabados** [comment]
Hi Arseniy,

I have some questions related to your commit.

1)
I believe the dependency tree should be handled in the opposite direction.

For example lets say module A imports from module B, and module B imports from module C ... if I delete all definitions (but the imports) from module B.
If I understand your algorithm correctly it would parse module B (the changed module) and module C (imported by module B) ... and leave out module A as it is not imported by either B or C.

But actually deleting the definitions from module B can not hurt C (as it does not depend on B) and can hurt module A (as the imported and used definition - for example a type- was deleted from B).
If you don't parse module A in this situation, you will not notice that some definitions in it (that depended on module B's definition) are no longer valid ... but will result in compilation problems on GCC level.
So the import hierarchy has to be processed backwards to identify which module's content could have become invalid.
To build this import hierarchy you need to parse all modules, as 1 module only tells what it needs, but does not directly tell, which modules import itself.
At which point you are again forced to parse all of the modules to get all of their imports ... and could not save on this time.

2)
If I'm miss-understanding something could you please provide us with some examples to see how your algorithm works?

3)
Please don't use getopt_long ... it does not exist on all of the platform we are supporting (for example older solaris versions). 
For the same reason we try to use as little std:: collections as possible (some very old GCC versions did not properly support them).

**Comment by ars3niy** [comment]
> Please don't use getopt_long ... it does not exist on all of the platform we are supporting (for example older solaris versions).

Then how about reimplementing getopt_long, or copy-pasting it from somewhere? It looks like you can run out of alphabet soon.

> module A imports from module B, and module B imports from module C ... and I delete all definitions (but not the imports) from module B. If I understand your algorithm correctly it would parse module B (the changed module) and module C (imported by module B) ... and leave out module A as it is not imported by either B or C.

However, if separate dependency tracking mechanism tells the compiler to rebuild module A (by putting it after dash) after detecting changes in B, then everything will be fine. At which point I can add another option: don't generate code for modules that are older than their .cc / .hh files even if told to.

Said dependency tracking would itself not be a part of the compiler but would require the compiler to generate dependency files when building modules (like gcc -M<...>), for which I'll send some more patches soon.

**Comment by ars3niy** [comment]
> for which I'll send some more patches soon

Or maybe I won't. I have those other patches already but it might be possible to deduce TTCN/ASN dependencies from output of actual gcc -M on the generated .cc files instead. Got to consider this.

**Comment by KristofSzabados** [comment]
Running out of the alphabet is a valid issue, so adding new features with new letter requirement needs to be considered carefully.

Please note the compiler already does not generate .hh/.cc files that would have the same content. .hh/.cc files are only overwritten if the content we would write into them, would be different from the one already present. This way if you do incremental build you can already save most of the build time (but linking can not take advantage of this, and badly structured source code can have import hierarchy that reduces the potential of parallel build.)

I'm also interested in your usecase.
In our experience the compiler's execution is only a small part of the build process (for 1 million lines of TTCN-3 code out of 30-50 minutes only ~1 minute is the compiler running. Mostly C++ compilation and linking taking the longest even on server machines).
In the development IDE ( Designer ) we have an improved version, where only the changed file needs to be re-parsed (or only a few lines of code from it) ... so we get < 1 sec re-checks.
This way users usually have seamless feadback ... but at the cost of more memory usage.

(I'm not trying to talk you down from your commit, just trying to have a better understanding)

**Comment by ars3niy** [comment]
My use case is people using Vim to edit and make to build. We have 500 huge .ttcn files which are test suites, they don't import each other but each import a bunch of smaller TTCN/ASN modules from test framework. When just one test suite is changed, which very common, full parsing takes 2 minutes, parsing with my --parse-less is 5 seconds, and C++ compilation and linking is 20 seconds.

**Comment by KristofSzabados** [comment]
Hmm ... usually we see very complex dependency trees,

In your case maybe some external solution would be the best.
If I understand correctly your situation only requires 2 ways from the makefile to work.
You can have the first (complete) build as usual, but afterwards you would only need to process a small subset of the project (as long as you don't have a more complex software architecture).

Maybe one way to make this happen would be to extend the generated makefile with a special target, that takes the name of the file to check ... and this would call the compiler with the provided name and files names from referenced projects. This way from you top-level project only the provided file would be checked.
But it might also be possible to automatically find out which files need re-parsing in your hierarchy so that you don't need to add that as parameter.
So with some external logic based on your situation you could make the makefile decide what to parse and hand them to the compiler, this way the compiler could remain working for all situation (and not even need a new option).

**Comment by ars3niy** [comment]
For any kind of external logic to work, I might still need the compiler to generate dependency files if mapping the dependencies from those of the generated .cc files proves unsatisfactory.

Also, I still think option to skip code generation for source files that are older than their .cc will be needed. Right now the compiler would spend time generating code and comparing it to the existing .cc file, and I don't want it to spend that time.

**Comment by KristofSzabados** [comment]
When the compiler internally generates the content to be possibly printed ... it is done in-memory.
And this is one thing where you would need a perfect control of dependency between assignments to be on the safe side.

For example the compiler support constant folding. This means that expressions with const values are calculated in compilation time and generated into the C++ code (this creates a good improvement in the runtime speed ... as in such situations nothing needs to be done in the runtime).
For the code generation this means, that if you have something like "const integer a1 := 1;" in module A and "const integer b1 := a1 + 1;" in module B (which imports A) ... the code generated to module B will effectively assign the value 2 to b1 (not even the addition is generated).
When in this setup you change the value of a1 to 5 in the source code, that will automatically mean that the value to be generated for b1 also changes to 6 ... yet module B was not changed directly, so moduleB.ttcn will be behind moduleB.{hh/cc}. If the compiler does not use the content to decide if the existing file needs to be overwritten or not ... that can lead to inconsistent output and unreliable test verdicts.

**Comment by KristofSzabados** [comment]
I just remembered that Titanium is already able to generate the module import hierarchy into pajek's .net and graphwiz's .dot format.
Maybe you could use that as input to decide which files to pass on to the compiler for compilation.

This does come at the need to keeping the hierarchy uptodate outside of the compiler ... but it might not change as often as the code (and the whole method of checking only a subset of the sourcecodes already comes with this risk anyway).

**Comment by ars3niy** [comment]
I would still like the functionality of this patch to be included if at all possible. A priori assumptions about module dependencies (that is, the fact that I know I have a lot of modules that are not being imported) don't speed things up as much as I would like to. When I have a set of modules that either have changed or depend on modules that have changed, I would still like to skip parsing modules that this set does not depend on, and that can only be achieved either by something like this patch, or by keeping the hierarchy up to date manually outside of the compiler, and we don't want to do the latter.

Another option would be to make the compiler multi-threaded. It would not help when a lot of people build their stuff on the same machine at the same time, but when they don't, a speedup would be pretty good. Is that something worth considering?

**Comment by ars3niy** [comment]
To recap, here is what I'm proposing. Let's say there are 4 modules, A imports B, B imports C, and D is on its own. The whole thing has been built, the compiler has generated dependency files so the build system knows the dependencies.

Module B is changed. The build system sees that, and also that module A depends on it, and tells the compiler to rebuild modules A and B. At this point, however, we no longer know the dependencies of module B, because we have the old dependency file and the module could have changed to import D as well. Therefore, it's up to the compiler to figure out which modules are imported by A and B and parse (but not generate code for) them.

How does it sound?

**Comment by KristofSzabados** [comment]
Well...

The current solution is building on assumptions that immediately break in other projects. So we would rather not include it in the product (also meaning offering it to other users).

Keeping the dependency up-to-date outside of the compiler is understandably a hard thing to do. In general that would mean the re-implementation of the compiler ( or a big part of it). From what you described your project structure might be simple enough to do this outside (assuming you really have only a few dependencies and they don't change often) ... but as you see it is quite problematic to keep it in sync and safe.
On the other hand handling the dependency in the compiler ... is what the compiler is doing now. To see what exactly depends on what requires the parsing or all modules. Missing definitions might have appeared, existing types might have changed (this can go up the whole hierarchy if it is embedded into a new type or used as formal parameter).

Making the compiler multi-threaded is very a costly operation (mostly because of all the things that could go wrong). And most probably would not bring that much benefit to the entire build process (finding optimization opportunities in the generated C++ code could provide more benefits ... I'm also working with university students and somehow they always notice something very nice ).

---
Please note that the compiler is already only generating code for modules whose could would change.
If the existing content of the .hh/.cc files is the same as what we would like to generate, they are not overwritten (not even touched) ... so gcc/clang is not activated for them.
Reading a stream of characters and comparing them to an array of characters is much faster than a gcc/clang compilation.

As it is the content to be generated that needs to differ, if you change a comment without any change to the code or its structure (like entering a space) there might actually be no change to any .hh/.cc file at all.

**Comment by ars3niy** [comment]
> The current solution is building on assumptions that immediately break in other projects. So we would rather not include it in the product (also meaning offering it to other users).

Can you please clarify which assumptions break in other projects? I'm trying to build my solution based on concepts that work flawlessly in build systems for C++ and such.

> Keeping the dependency up-to-date outside of the compiler is understandably a hard thing to do

Fortunately, there is no need to keep it exactly up to date. It's enough to keep it up to date just for those modules that haven't changed since the last build, and that can easily be done automatically.

> Please note that the compiler is already only generating code for modules whose could would change.

However, it will parse (and maybe even do semantic check on?) all modules, and that already takes too long in many incremental build scenarios.

> finding optimization opportunities in the generated C++ code could provide more benefits

For complete builds, yes, but C++ compilation can be much less important during incremental builds. In a common incremental build scenario I'm facing, this patch cuts TTCN/ASN translation time from 2 minutes down to 5 seconds while C++ compilation takes 20 seconds. In other words, speeding up C++ compilation by a factor of 2, which would be an unbelievable achievement, would speed up this incremental build by less than 10%, as opposed to factor of 3 or more speedup from the enhanced dependency tracking I'm trying to propose.

**Comment by KristofSzabados** [comment]
One concept that breaks in other projects is that you only need to re-check and re-build the file you changed. This is exactly the same in C++: if you change a .hh file, you should rebuild every .cc that directly or indirectly includes it. Otherwise your code might not link together, or worse link but produce issues at runtime.
This is the same in this case, if you change a module you also need to re-check and re-build all modules that directly or indirectly import it. Mostly because modules are generated into .hh and .cc file.
And in general TTCN-3 based projects follow [scale-free properties in their import graph](https://www.researchgate.net/publication/221047120_Structural_Analysis_of_Large_TTCN-3_Projects), just like other languages they are so densely linked, that even [drawing in 2D](https://www.researchgate.net/publication/304785920_Titanium_Visualization_of_TTCN-3_system_architecture) can be problematic.

If your dependencies are as simple as you described and they don't change too often, you could keep track of them externally from the makefile.
In which case you could write a small tool to just use that information to decide which files to pass on to the compiler, for re-compilation.
This way you could control what files it sees resulting in what files it parses and checks.
And on this way the compiler could stay safe for every user and project.
Please note, the Titanium tool is able to export the import graph into pajek's .net of graphwiz's .dot format so your tool could use them.

**Comment by ars3niy** [comment]
> One concept that breaks in other projects is that you only need to re-check and re-build the file you changed. 

But I have abandoned that one.

An external tool will take the set of modules that have changed, build set of modules that have not changed but import those that have (directly or through a chain of other modules), and feed union of these two sets to the compiler. The compiler will parse, check and rebuild all that, plus parse and check (but not build) modules imported (directly or through a chain of other modules) by the modules that need to be built. For that last "plus parse and check" part, I need this patch.

This way, the parse-less option I'm proposing should (I think) always result in correct rebuilds as long as the build system feeds the correct subset of modules to the compiler. Sure, the option can only be used in conjunction with such build system, but that should be fine if it's well documented.

**Comment by KristofSzabados** [comment]
Yes, if that build system is also present this could work.
Could you please do that?

The current implementation is just the last part of it. Without the preceding system to filter out the files (safely and correctly) it cannot be offered as production ready. As it is just not possible to say that users can use this option in a no-touch CI system and get the exact same results as the full build would give, irrespective of the structure of the project and the location of the change.

If you can make the part that feeds to the compiler only the files that need to be parsed, that could work ... and maybe offered as a new makefile target. (please note it will still need some testing and stuff before we can include it)

**Comment by ars3niy** [comment]
> Yes, if that build system is also present this could work. Could you please do that?

If you mean integrating this "feeding to the compiler" logic to the makefile skeleton generated by the compiler, I'll get back to you on that because that might require additional patches to the compiler with gcc -M like functionality.

In the meantime, can we start integrating this patch, maybe without documenting the option?

**Comment by ars3niy** [comment]
For what it's worth, here is an example of a makefile that seems to achieve the require dependency tracking: https://pastebin.com/FpmQ1pWA

**Comment by KristofSzabados** [comment]
Do I understand it correctly that you would like to use the incremental dependency tracking feature already supported in Titan?
If you run the makefile generator with the -g flag to produce makefile for GNU makes, the generated makefile will by default  use .d files to track the dependencies of the source files, incrementally.
(Makefiles are not so easy to understand, could you make an example on how you would modify a makefile generated by Titan for gnu makes with the incrementally refreshing dependencies?)

**Comment by KristofSzabados** [comment]
Hi ars3niy,
Although you are moving in the right direction, I need to close this request.

But please don't give up, it would be great if this feature could be available in a reliable way.
For it to work like that it has to be:
- available for everyone, having however complex project structure they might have (even layered builds)
- incremental build must give the same result as a full build, just faster. This means that however complex the project is, whatever was last time generated and however large and wide spreading effect the current change has, the result must still be the same executable as if this was a complete build from zero.
- this also means that the solution must not only work in good cases, but also for bad inputs. If the user created some syntactical or semantic errors those must be detected and reported. Even if the side effect of the change has to travel through several modules to create an issue (like a modified field type can travel via type references, or a change constant value via successive constant evaluations, etc...)

- also the change has to be a consistent change across the toolset so that people can use it: not only the code of the compiler needs to be changed, but also the makefile generator needs to be able to produce correct makefiles, new flags/modes need to be stored in TPD files (so that the makefile generator knows of them), the user interfaces need to be extended (so that the users can update them in command line and in eclipse), documentation must be updated so users can learn how and what it does, etc...

**Pull request closed without merging**
